const QUESTIONS = {
  Geography: [
    { q: "What is the capital of Australia?", choices: ["Sydney", "Canberra", "Melbourne", "Perth"], correctIndex: "2" },
    { q: "Which is the largest ocean on Earth?", choices: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], correctIndex: "3" },
    { q: "Which country has the largest population?", choices: ["India", "China", "USA", "Russia"], correctIndex: "2" },
    { q: "What is the longest river in the world?", choices: ["Amazon", "Nile", "Yangtze", "Mississippi"], correctIndex: "2" },
    { q: "Which continent is Egypt in?", choices: ["Asia", "Africa", "Europe", "South America"], correctIndex: "2" },
    { q: "What is the capital of France?", choices: ["Paris", "Lyon", "Marseille", "Nice"], correctIndex: "1" },
    { q: "Mount Everest is located in which mountain range?", choices: ["Andes", "Rockies", "Himalayas", "Alps"], correctIndex: "3" },
    { q: "Which US state is the Grand Canyon located in?", choices: ["Utah", "Arizona", "Nevada", "Colorado"], correctIndex: "2" },
    { q: "Which European country has the most people?", choices: ["Germany", "France", "UK", "Italy"], correctIndex: "1" },
    { q: "What is the capital of Japan?", choices: ["Osaka", "Tokyo", "Kyoto", "Hiroshima"], correctIndex: "2" },
    { q: "Which desert is the largest hot desert in the world?", choices: ["Gobi", "Sahara", "Kalahari", "Mojave"], correctIndex: "2" },
    { q: "Which river runs through London?", choices: ["Thames", "Seine", "Danube", "Rhine"], correctIndex: "1" },
    { q: "Which country is the island of Borneo shared by?", choices: ["Indonesia, Malaysia, Brunei", "Philippines, Indonesia", "Malaysia, Thailand", "Brunei, Philippines"], correctIndex: "1" },
    { q: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], correctIndex: "3" },
    { q: "Which country contains the city of Marrakech?", choices: ["Algeria", "Morocco", "Tunisia", "Egypt"], correctIndex: "2" },
    { q: "Which U.S. city is famous for its Golden Gate Bridge?", choices: ["Los Angeles", "San Francisco", "Seattle", "San Diego"], correctIndex: "2" },
    { q: "Which is the smallest country by area?", choices: ["Monaco", "Nauru", "Vatican City", "San Marino"], correctIndex: "3" },
    { q: "Which African country has the largest land area?", choices: ["Egypt", "Algeria", "Sudan", "Libya"], correctIndex: "2" },
    { q: "Which ocean is on the east coast of the United States?", choices: ["Pacific", "Atlantic", "Indian", "Arctic"], correctIndex: "2" },
    { q: "Which country has cities named Córdoba and Seville?", choices: ["Portugal", "Spain", "Mexico", "Argentina"], correctIndex: "2" },
    { q: "The Rhine river flows into which sea?", choices: ["Baltic Sea", "North Sea", "Mediterranean Sea", "Black Sea"], correctIndex: "2" },
    { q: "Which country is famous for the fjords?", choices: ["Sweden", "Norway", "Finland", "Denmark"], correctIndex: "2" },
    { q: "What is the capital of Italy?", choices: ["Venice", "Rome", "Florence", "Milan"], correctIndex: "2" },
    { q: "Which country is the Taj Mahal located in?", choices: ["Pakistan", "India", "Bangladesh", "Nepal"], correctIndex: "2" },
    { q: "Which US state is known as the 'Sunshine State'?", choices: ["California", "Florida", "Texas", "Arizona"], correctIndex: "2" },
    { q: "Which continent is Chile located in?", choices: ["South America", "North America", "Africa", "Europe"], correctIndex: "1" },
    { q: "Which city is the capital of Germany?", choices: ["Munich", "Frankfurt", "Berlin", "Hamburg"], correctIndex: "3" },
    { q: "Which country has the most natural lakes?", choices: ["Canada", "USA", "Russia", "Finland"], correctIndex: "1" },
    { q: "What is the capital of Russia?", choices: ["Saint Petersburg", "Moscow", "Kazan", "Sochi"], correctIndex: "2" },
    { q: "Which mountain is the highest in Africa?", choices: ["Mount Kenya", "Kilimanjaro", "Rwenzori", "Atlas"], correctIndex: "2" },
    { q: "Which river flows through Paris?", choices: ["Seine", "Loire", "Rhône", "Garonne"], correctIndex: "1" },
    { q: "Which country is known as the Land of the Rising Sun?", choices: ["China", "Japan", "Korea", "Thailand"], correctIndex: "2" },
    { q: "Which European capital is built on approximately 118 islands?", choices: ["Stockholm", "Helsinki", "Copenhagen", "Oslo"], correctIndex: "1" },
    { q: "Which country contains the lakes of Plitvice?", choices: ["Croatia", "Slovenia", "Bosnia", "Serbia"], correctIndex: "1" },
    { q: "Which is the largest island in the Mediterranean Sea?", choices: ["Sardinia", "Sicily", "Corsica", "Crete"], correctIndex: "2" },
    { q: "What is the capital of Brazil?", choices: ["Rio de Janeiro", "Brasília", "São Paulo", "Salvador"], correctIndex: "2" },
    { q: "Which country has Tokyo Bay?", choices: ["South Korea", "Japan", "China", "Philippines"], correctIndex: "2" },
    { q: "Which city is known as the 'Big Apple'?", choices: ["Los Angeles", "Chicago", "New York City", "Miami"], correctIndex: "3" },
    { q: "Which African river has the largest discharge?", choices: ["Nile", "Congo", "Zambezi", "Niger"], correctIndex: "2" },
    { q: "Which country has the Great Barrier Reef off its coast?", choices: ["Australia", "Indonesia", "Philippines", "Fiji"], correctIndex: "1" },
    { q: "What is the capital of Argentina?", choices: ["Córdoba", "Buenos Aires", "Rosario", "Mendoza"], correctIndex: "2" },
    { q: "Which gulf is east of the Arabian Peninsula?", choices: ["Persian Gulf", "Gulf of Oman", "Gulf of Aden", "Red Sea"], correctIndex: "2" },
    { q: "Which city lies at the junction of the Blue and White Nile?", choices: ["Khartoum", "Cairo", "Khartoum North", "Omdurman"], correctIndex: "1" },
    { q: "Which country is the largest by area?", choices: ["Canada", "China", "USA", "Russia"], correctIndex: "4" },
    { q: "What is the official language of Brazil?", choices: ["Spanish", "Portuguese", "English", "French"], correctIndex: "2" },
    { q: "Which European country is known for windmills and tulips?", choices: ["Belgium", "Netherlands", "Denmark", "Germany"], correctIndex: "2" },
    { q: "Which US state is the largest by area?", choices: ["Texas", "California", "Alaska", "Montana"], correctIndex: "3" },
    { q: "Which city is the capital of Turkey?", choices: ["Istanbul", "Ankara", "Izmir", "Bursa"], correctIndex: "2" },
    { q: "Which country is famous for the fjords of Geiranger?", choices: ["Sweden", "Norway", "Iceland", "Denmark"], correctIndex: "2" },
    { q: "Which strait separates Europe and Asia at Istanbul?", choices: ["Strait of Hormuz", "Bosporus", "English Channel", "Strait of Gibraltar"], correctIndex: "2" },
    { q: "Which African country has Cape Town as a major city?", choices: ["Zimbabwe", "South Africa", "Namibia", "Botswana"], correctIndex: "2" },
    { q: "Which country contains the ancient city of Petra?", choices: ["Jordan", "Lebanon", "Israel", "Syria"], correctIndex: "1" },
    { q: "Which mountain range runs across Morocco and Algeria?", choices: ["Alps", "Atlas", "Carpathians", "Pyrenees"], correctIndex: "2" },
    { q: "Which body of water lies between Saudi Arabia and Africa?", choices: ["Red Sea", "Persian Gulf", "Gulf of Oman", "Arabian Sea"], correctIndex: "1" },
    { q: "Which US city is the capital of California?", choices: ["San Francisco", "Los Angeles", "Sacramento", "San Diego"], correctIndex: "3" },
    { q: "Which country is the island of Madagascar off?", choices: ["Mozambique", "South Africa", "Tanzania", "Kenya"], correctIndex: "1" },
    { q: "Which country has the most UNESCO World Heritage sites?", choices: ["Italy", "China", "Spain", "France"], correctIndex: "1" },
    { q: "Which desert lies in northern China and southern Mongolia?", choices: ["Sahara", "Gobi", "Karakum", "Taklamakan"], correctIndex: "2" },
    { q: "Which country has the capital city Nairobi?", choices: ["Uganda", "Kenya", "Tanzania", "Ethiopia"], correctIndex: "2" },
    { q: "Which sea is located between Italy and the Balkan Peninsula?", choices: ["Adriatic Sea", "Aegean Sea", "Tyrrhenian Sea", "Ionian Sea"], correctIndex: "1" },
    { q: "Which is the longest mountain range above sea level?", choices: ["Rockies", "Andes", "Himalayas", "Alps"], correctIndex: "2" },
    { q: "Which country uses the peso currency (Latin America)?", choices: ["Brazil", "Argentina", "Mexico", "Peru"], correctIndex: "3" },
    { q: "What is the capital of South Korea?", choices: ["Busan", "Seoul", "Incheon", "Daegu"], correctIndex: "2" },
    { q: "Which country has the city of Reykjavik?", choices: ["Greenland", "Iceland", "Ireland", "Norway"], correctIndex: "2" },
    { q: "Which river is the longest in South America?", choices: ["Amazon", "Paraná", "Orinoco", "Magdalena"], correctIndex: "1" },
    { q: "Which city is known as the 'City of Canals' and built on water?", choices: ["Venice", "Amsterdam", "Bruges", "Stockholm"], correctIndex: "1" },
    { q: "Which country contains the ancient ruins of Machu Picchu?", choices: ["Peru", "Bolivia", "Chile", "Ecuador"], correctIndex: "1" },
    { q: "Which country is Tokyo the capital of?", choices: ["South Korea", "China", "Japan", "Taiwan"], correctIndex: "3" },
    { q: "The Ural Mountains separate which two continents?", choices: ["Asia and Africa", "Europe and Asia", "North and South America", "Europe and Africa"], correctIndex: "2" },
    { q: "Which city is the capital of India?", choices: ["Delhi", "Mumbai", "Kolkata", "Bangalore"], correctIndex: "1" },
    { q: "Which country is home to the city of Dubrovnik?", choices: ["Croatia", "Bosnia", "Montenegro", "Slovenia"], correctIndex: "1" },
    { q: "Which gulf lies southeast of India?", choices: ["Gulf of Mexico", "Gulf of Oman", "Gulf of Thailand", "Bay of Bengal"], correctIndex: "4" },
    { q: "Which Central American country has Panama City as its capital?", choices: ["Costa Rica", "Panama", "Guatemala", "Honduras"], correctIndex: "2" },
    { q: "Which sea lies to the north of Turkey?", choices: ["Black Sea", "Mediterranean Sea", "Red Sea", "Aegean Sea"], correctIndex: "1" },
    { q: "Which country has the city of Lagos?", choices: ["Ghana", "Nigeria", "Cameroon", "Senegal"], correctIndex: "2" },
    { q: "Which country is known for its fjords and the city Bergen?", choices: ["Norway", "Iceland", "Scotland", "Sweden"], correctIndex: "1" },
    { q: "What is the capital of Thailand?", choices: ["Phuket", "Bangkok", "Chiang Mai", "Pattaya"], correctIndex: "2" },
    { q: "Which country is made up of thousands of islands including Luzon and Mindanao?", choices: ["Indonesia", "Philippines", "Malaysia", "Japan"], correctIndex: "2" },
    { q: "Which large bay lies on the east coast of Australia?", choices: ["Moreton Bay", "Sydney Bay", "Botany Bay", "Great Australian Bight"], correctIndex: "4" },
    { q: "Which city is the capital of Portugal?", choices: ["Lisbon", "Porto", "Braga", "Coimbra"], correctIndex: "1" },
    { q: "Which is the smallest continent by area?", choices: ["Europe", "Antarctica", "Australia", "South America"], correctIndex: "3" },
    { q: "Which country borders both the Atlantic and Pacific Oceans?", choices: ["Chile", "Mexico", "Panama", "Colombia"], correctIndex: "3" },
    { q: "Which US state has the city of Anchorage?", choices: ["Alaska", "Hawaii", "Washington", "Oregon"], correctIndex: "1" },
    { q: "Which sea borders Egypt to the north?", choices: ["Red Sea", "Mediterranean Sea", "Arabian Sea", "Black Sea"], correctIndex: "2" },
    { q: "Which country is home to the Dead Sea?", choices: ["Israel and Jordan", "Egypt", "Syria", "Lebanon"], correctIndex: "1" },
    { q: "Which city is the capital of Saudi Arabia?", choices: ["Jeddah", "Mecca", "Riyadh", "Dammam"], correctIndex: "3" },
    { q: "Which region is known as the 'Outback'?", choices: ["Central Australia", "Northern Canada", "Sahara fringe", "Patagonia"], correctIndex: "1" },
    { q: "Which US river forms part of the border between the USA and Mexico?", choices: ["Colorado River", "Mississippi", "Rio Grande", "Columbia"], correctIndex: "3" },
    { q: "What is the capital of Sweden?", choices: ["Gothenburg", "Stockholm", "Malmö", "Uppsala"], correctIndex: "2" },
    { q: "Which country is famous for the Angkor Wat temple?", choices: ["Thailand", "Cambodia", "Vietnam", "Laos"], correctIndex: "2" },
    { q: "Which country contains the region of Bavaria?", choices: ["Austria", "Germany", "Switzerland", "Czech Republic"], correctIndex: "2" },
    { q: "Which large sea borders Italy to the south?", choices: ["Ionian Sea", "Baltic Sea", "Black Sea", "Caspian Sea"], correctIndex: "1" },
    { q: "Which city is the capital of Malaysia?", choices: ["George Town", "Kuala Lumpur", "Malacca", "Putrajaya"], correctIndex: "2" },
    { q: "Which country is the world's largest archipelago by number of islands?", choices: ["Indonesia", "Philippines", "Sweden", "Finland"], correctIndex: "1" },
    { q: "Which volcano destroyed the Roman city of Pompeii?", choices: ["Vesuvius", "Etna", "Stromboli", "Krakatoa"], correctIndex: "1" },
    { q: "Which river runs through Baghdad?", choices: ["Euphrates", "Tigris", "Jordan", "Orontes"], correctIndex: "2" },
    { q: "Which African country was formerly known as Abyssinia?", choices: ["Ethiopia", "Somalia", "Eritrea", "Sudan"], correctIndex: "1" },
    { q: "Which US city is built on seven hills and famous for the Golden Gate?", choices: ["San Francisco", "Seattle", "San Diego", "Boston"], correctIndex: "1" },
    { q: "Which sea lies between Italy and Greece?", choices: ["Ionian Sea", "North Sea", "Baltic Sea", "Red Sea"], correctIndex: "1" },
    { q: "Which country has the city of Casablanca?", choices: ["Algeria", "Morocco", "Tunisia", "Libya"], correctIndex: "2" },
    { q: "What is the capital of New Zealand?", choices: ["Auckland", "Wellington", "Christchurch", "Dunedin"], correctIndex: "2" },
    { q: "Which island country is southeast of India and has Colombo as a major city?", choices: ["Sri Lanka", "Maldives", "Mauritius", "Seychelles"], correctIndex: "1" },
    { q: "Which river is closely associated with Cairo and ancient Egypt?", choices: ["Tigris", "Euphrates", "Nile", "Jordan"], correctIndex: "3" },
    { q: "Which mountain range forms the 'backbone' of Italy?", choices: ["Alps", "Apennines", "Pyrenees", "Dinaric Alps"], correctIndex: "2" },
    { q: "Which country is bordered by both the Caribbean Sea and the Pacific Ocean?", choices: ["Colombia", "Venezuela", "Cuba", "Haiti"], correctIndex: "1" },
    { q: "Which city is capital of Greece?", choices: ["Thessaloniki", "Patras", "Athens", "Heraklion"], correctIndex: "3" }
  ],

  Science: [
    { q: "What is the chemical symbol for water?", choices: ["HO", "H2O", "O2", "H2"], correctIndex: "2" },
    { q: "What gas do plants absorb from the atmosphere?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctIndex: "2" },
    { q: "What part of the cell contains DNA?", choices: ["Nucleus", "Mitochondria", "Ribosome", "Cytoplasm"], correctIndex: "1" },
    { q: "What force pulls objects toward Earth?", choices: ["Magnetism", "Gravity", "Inertia", "Friction"], correctIndex: "2" },
    { q: "What is the boiling point of water?", choices: ["50°C", "100°C", "150°C", "200°C"], correctIndex: "2" },
    { q: "What is the chemical symbol for table salt (sodium chloride)?", choices: ["NaCl", "KCl", "ClNa", "NaK"], correctIndex: "1" },
    { q: "What organ pumps blood through the body?", choices: ["Liver", "Kidney", "Heart", "Lungs"], correctIndex: "3" },
    { q: "Which planet is known as the Red Planet?", choices: ["Venus", "Mars", "Jupiter", "Mercury"], correctIndex: "2" },
    { q: "What is the center of an atom called?", choices: ["Electron", "Proton", "Nucleus", "Neutron"], correctIndex: "3" },
    { q: "Which gas do humans breathe out?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], correctIndex: "2" },
    { q: "What type of bond involves sharing electron pairs?", choices: ["Ionic", "Covalent", "Metallic", "Hydrogen"], correctIndex: "2" },
    { q: "What is the study of living organisms called?", choices: ["Physics", "Chemistry", "Biology", "Geology"], correctIndex: "3" },
    { q: "Which organelle is the powerhouse of the cell?", choices: ["Ribosome", "Mitochondria", "Nucleus", "Golgi apparatus"], correctIndex: "2" },
    { q: "What kind of celestial object is the Sun?", choices: ["Planet", "Star", "Moon", "Asteroid"], correctIndex: "2" },
    { q: "What is the chemical formula for carbon dioxide?", choices: ["CO", "CO2", "O2", "C2O"], correctIndex: "2" },
    { q: "What is the unit of electrical current?", choices: ["Volt", "Ohm", "Ampere", "Watt"], correctIndex: "3" },
    { q: "Which particle has a negative charge?", choices: ["Proton", "Neutron", "Electron", "Photon"], correctIndex: "3" },
    { q: "Which planet has the most moons (as of common knowledge)?", choices: ["Earth", "Mars", "Jupiter", "Venus"], correctIndex: "3" },
    { q: "Which gas makes up most of Earth's atmosphere?", choices: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide"], correctIndex: "3" },
    { q: "What is the natural satellite of the Earth?", choices: ["Mars", "Moon", "Venus", "Jupiter"], correctIndex: "2" },
    { q: "What is the primary source of energy for the water cycle?", choices: ["Wind", "Sun", "Moon", "Geothermal"], correctIndex: "2" },
    { q: "Which scale measures the acidity of a solution?", choices: ["Fahrenheit", "pH", "Richter", "Decibel"], correctIndex: "2" },
    { q: "What is the SI unit of temperature?", choices: ["Celsius", "Fahrenheit", "Kelvin", "Rankine"], correctIndex: "3" },
    { q: "Which element has the atomic number 1?", choices: ["Helium", "Hydrogen", "Lithium", "Carbon"], correctIndex: "2" },
    { q: "Which force keeps planets in orbit around the Sun?", choices: ["Magnetism", "Gravity", "Friction", "Electricity"], correctIndex: "2" },
    { q: "What is the process by which plants make food using sunlight?", choices: ["Respiration", "Photosynthesis", "Transpiration", "Fermentation"], correctIndex: "2" },
    { q: "Which type of wave is sound?", choices: ["Transverse", "Longitudinal", "Electromagnetic", "Torsional"], correctIndex: "2" },
    { q: "What is HCl in chemistry?", choices: ["Hydrochloric acid", "Hydrogen chloride gas", "Helium chloride", "Hydrated chloride"], correctIndex: "1" },
    { q: "Which organ filters blood to make urine?", choices: ["Liver", "Kidney", "Heart", "Lung"], correctIndex: "2" },
    { q: "Which planet is the largest in our solar system?", choices: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctIndex: "2" },
    { q: "What do you call a group of atoms bonded together?", choices: ["Element", "Molecule", "Ion", "Compound"], correctIndex: "2" },
    { q: "What is the study of rocks called?", choices: ["Biology", "Geology", "Meteorology", "Zoology"], correctIndex: "2" },
    { q: "Which part of the human body controls balance?", choices: ["Cerebellum", "Cortex", "Medulla", "Hypothalamus"], correctIndex: "1" },
    { q: "What is the common name for sodium bicarbonate?", choices: ["Baking soda", "Table salt", "Bleach", "Vinegar"], correctIndex: "1" },
    { q: "Which gas is essential for respiration?", choices: ["Helium", "Oxygen", "Nitrogen", "Methane"], correctIndex: "2" },
    { q: "Which device measures electric voltage?", choices: ["Ammeter", "Voltmeter", "Barometer", "Thermometer"], correctIndex: "2" },
    { q: "Which phenomenon causes a straw in a glass to appear bent?", choices: ["Reflection", "Refraction", "Diffraction", "Interference"], correctIndex: "2" },
    { q: "What connects muscles to bones?", choices: ["Ligaments", "Tendons", "Cartilage", "Fascia"], correctIndex: "2" },
    { q: "Which organ produces insulin?", choices: ["Liver", "Pancreas", "Kidney", "Gallbladder"], correctIndex: "2" },
    { q: "Which metal is liquid at room temperature?", choices: ["Mercury", "Iron", "Aluminum", "Gold"], correctIndex: "1" },
    { q: "What is the pH of a neutral solution (water) at 25°C?", choices: ["0", "7", "14", "3"], correctIndex: "2" },
    { q: "Which unit is used to measure energy?", choices: ["Newton", "Watt", "Joule", "Pascal"], correctIndex: "3" },
    { q: "Which scientist proposed the three laws of motion?", choices: ["Einstein", "Newton", "Galileo", "Maxwell"], correctIndex: "2" },
    { q: "What is the main gas responsible for the greenhouse effect?", choices: ["Oxygen", "Carbon dioxide", "Nitrogen", "Helium"], correctIndex: "2" },
    { q: "Which blood cells help fight infection?", choices: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], correctIndex: "2" },
    { q: "What is the basic unit of life?", choices: ["Atom", "Molecule", "Cell", "Organ"], correctIndex: "3" },
    { q: "Which vitamin is produced when skin is exposed to sunlight?", choices: ["Vitamin A", "Vitamin B12", "Vitamin D", "Vitamin C"], correctIndex: "3" },
    { q: "Which astronomical event occurs when the Moon passes between Earth and the Sun?", choices: ["Lunar eclipse", "Solar eclipse", "Meteor shower", "Conjunction"], correctIndex: "2" },
    { q: "Which molecule carries genetic information?", choices: ["RNA", "ATP", "DNA", "Enzyme"], correctIndex: "3" },
    { q: "What is the study of weather called?", choices: ["Climatology", "Meteorology", "Geology", "Oceanography"], correctIndex: "2" },
    { q: "Which type of radiation is the most energetic?", choices: ["Radio", "Microwave", "Gamma rays", "Visible light"], correctIndex: "3" },
    { q: "Which instrument is used to look at stars and planets?", choices: ["Microscope", "Telescope", "Periscope", "Spectrometer"], correctIndex: "2" },
    { q: "Which process turns liquid water into vapor?", choices: ["Condensation", "Freezing", "Evaporation", "Sublimation"], correctIndex: "3" },
    { q: "Which particle has no electric charge?", choices: ["Proton", "Electron", "Neutron", "Positron"], correctIndex: "3" },
    { q: "Which organ is primarily responsible for digestion of proteins?", choices: ["Stomach", "Small intestine", "Liver", "Pancreas"], correctIndex: "1" },
    { q: "What is the nearest star to Earth?", choices: ["Alpha Centauri", "Sirius", "Proxima Centauri", "The Sun"], correctIndex: "4" },
    { q: "Which field studies the relationships between organisms and their environment?", choices: ["Anatomy", "Ecology", "Genetics", "Botany"], correctIndex: "2" },
    { q: "Which gas is used in balloons to make them float?", choices: ["Oxygen", "Nitrogen", "Hydrogen", "Helium"], correctIndex: "4" },
    { q: "Which device detects ionizing radiation?", choices: ["Thermometer", "Geiger counter", "Voltmeter", "Barometer"], correctIndex: "2" },
    { q: "What is the main component of natural gas?", choices: ["Ethane", "Methane", "Propane", "Butane"], correctIndex: "2" },
    { q: "Which biological molecule is an enzyme made of?", choices: ["Nucleic acid", "Lipid", "Protein", "Carbohydrate"], correctIndex: "3" },
    { q: "Which organ helps oxygenate blood?", choices: ["Kidney", "Lung", "Liver", "Spleen"], correctIndex: "2" },
    { q: "Which scale measures earthquake strength?", choices: ["Fujita", "Richter", "Beaufort", "Decibel"], correctIndex: "2" },
    { q: "What is the major component of steel?", choices: ["Iron", "Copper", "Aluminum", "Gold"], correctIndex: "1" },
    { q: "Which property measures how much matter an object contains?", choices: ["Weight", "Volume", "Mass", "Density"], correctIndex: "3" },
    { q: "Which sense organ detects light?", choices: ["Eye", "Ear", "Skin", "Nose"], correctIndex: "1" },
    { q: "What is the freezing point of water in Celsius?", choices: ["0°C", "32°C", "-1°C", "100°C"], correctIndex: "1" },
    { q: "Which element is required for combustion?", choices: ["Nitrogen", "Oxygen", "Carbon", "Helium"], correctIndex: "2" },
    { q: "Which gas is used by plants to perform photosynthesis?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"], correctIndex: "2" },
    { q: "Which branch studies motion and forces?", choices: ["Chemistry", "Biology", "Physics", "Astronomy"], correctIndex: "3" },
    { q: "Which organ produces bile?", choices: ["Kidney", "Liver", "Pancreas", "Spleen"], correctIndex: "2" },
    { q: "Which planet is closest to the Sun?", choices: ["Earth", "Mercury", "Venus", "Mars"], correctIndex: "2" }
  ],

  Sport: [
    { q: "How many players from one team are on the field in soccer?", choices: ["9", "10", "11", "12"], correctIndex: "3" },
    { q: "In basketball, how many points is a free throw worth?", choices: ["1", "2", "3", "4"], correctIndex: "1" },
    { q: "Which sport uses a shuttlecock?", choices: ["Tennis", "Badminton", "Squash", "Cricket"], correctIndex: "2" },
    { q: "How long is an Olympic swimming pool?", choices: ["25m", "50m", "75m", "100m"], correctIndex: "2" },
    { q: "In which sport do players hit a ball with a bat?", choices: ["Volleyball", "Hockey", "Cricket", "Rowing"], correctIndex: "3" },
    { q: "How many players are on a basketball team on the court?", choices: ["4", "5", "6", "7"], correctIndex: "2" },
    { q: "Which country hosted the 2016 Summer Olympics?", choices: ["China", "Brazil", "UK", "Russia"], correctIndex: "2" },
    { q: "How many minutes are in a standard soccer match (excluding extra time)?", choices: ["90", "60", "120", "45"], correctIndex: "1" },
    { q: "What sport uses a pommel horse?", choices: ["Diving", "Gymnastics", "Equestrian", "Wrestling"], correctIndex: "2" },
    { q: "What is a 'strike' in baseball?", choices: ["A missed catch", "A successful hit", "A failed swing or missed pitch", "A home run"], correctIndex: "3" },
    { q: "In tennis, what is the score when a player wins the point after deuce?", choices: ["Match", "Game", "Advantage", "Set"], correctIndex: "3" },
    { q: "Which sport is Roger Federer famous for?", choices: ["Golf", "Tennis", "Soccer", "Rugby"], correctIndex: "2" },
    { q: "What is the length of an NBA basketball court (in feet)?", choices: ["82", "94", "100", "110"], correctIndex: "2" },
    { q: "Which sport is known as the 'king of sports' globally?", choices: ["Cricket", "Basketball", "Tennis", "Football (soccer)"], correctIndex: "4" },
    { q: "How many players are on a rugby union team on the field?", choices: ["11", "13", "15", "7"], correctIndex: "3" },
    { q: "A 'hat-trick' in soccer means:", choices: ["Three assists", "Three goals by one player in a match", "Three appearances", "Three wins"], correctIndex: "2" },
    { q: "Which sport uses a puck?", choices: ["Tennis", "Ice hockey", "Field hockey", "Lacrosse"], correctIndex: "2" },
    { q: "How long is an Olympic marathon (approx.)?", choices: ["26.2 miles", "13.1 miles", "30 miles", "10 km"], correctIndex: "1" },
    { q: "Which country won the FIFA World Cup in 2018?", choices: ["Brazil", "Germany", "France", "Argentina"], correctIndex: "3" },
    { q: "In which sport would you use a javelin?", choices: ["Shot put", "Discus", "Javelin throw", "High jump"], correctIndex: "3" },
    { q: "What is the scoring method for a touchdown in American football?", choices: ["2 points", "3 points", "6 points", "1 point"], correctIndex: "3" },
    { q: "Which sport uses terms like 'birdie' and 'eagle'?", choices: ["Golf", "Tennis", "Badminton", "Cricket"], correctIndex: "1" },
    { q: "How many holes are there in a standard golf course?", choices: ["9", "12", "18", "24"], correctIndex: "3" },
    { q: "Which country hosted the 2012 Summer Olympics?", choices: ["China", "Brazil", "UK", "Russia"], correctIndex: "3" },
    { q: "How many periods are in an ice hockey game (professional)?", choices: ["2", "3", "4", "5"], correctIndex: "2" },
    { q: "Which sport uses a vault, rings, and parallel bars?", choices: ["Swimming", "Gymnastics", "Athletics", "Diving"], correctIndex: "2" },
    { q: "Which athlete is known for winning 9 Olympic gold medals in swimming (Michael Phelps)?", choices: ["Usain Bolt", "Michael Phelps", "Ian Thorpe", "Ryan Lochte"], correctIndex: "2" },
    { q: "Which country is famous for cricket and the Ashes rivalry with England?", choices: ["India", "Australia", "South Africa", "Pakistan"], correctIndex: "2" },
    { q: "What is the maximum score in ten-pin bowling for a single game?", choices: ["200", "250", "300", "350"], correctIndex: "3" },
    { q: "Which sport uses a 'tee' to start play?", choices: ["Tennis", "Cricket", "Golf", "Rugby"], correctIndex: "3" },
    { q: "Which country hosted the first modern Olympics in 1896?", choices: ["France", "Greece", "UK", "USA"], correctIndex: "2" },
    { q: "Which sport features the Tour de France?", choices: ["Running", "Cycling", "Swimming", "Rowing"], correctIndex: "2" },
    { q: "How many players are on a water polo team in the pool (per side)?", choices: ["5", "6", "7", "8"], correctIndex: "3" },
    { q: "Which sport uses terms like 'scrum' and 'try'?", choices: ["Rugby", "Soccer", "Cricket", "Basketball"], correctIndex: "1" },
    { q: "Which event is 100 meters long?", choices: ["Sprint", "Marathon", "Hurdles", "Relay"], correctIndex: "1" },
    { q: "Which country won the FIFA World Cup in 2014?", choices: ["Argentina", "Germany", "Brazil", "Spain"], correctIndex: "2" },
    { q: "Which sport's major tournament is Wimbledon?", choices: ["Football", "Tennis", "Cricket", "Golf"], correctIndex: "2" },
    { q: "How many players are in a baseball team on the field?", choices: ["7", "8", "9", "10"], correctIndex: "3" },
    { q: "Which sport uses a boccia ball?", choices: ["Boccia", "Bowling", "Curling", "Petanque"], correctIndex: "1" },
    { q: "Which sport measures performance with 'time' as the main factor?", choices: ["Gymnastics", "Athletics (running)", "Diving", "Figure skating"], correctIndex: "2" },
    { q: "Which country is widely known for producing great soccer players like Maradona and Messi?", choices: ["Brazil", "Argentina", "Portugal", "Spain"], correctIndex: "2" },
    { q: "In boxing, how many rounds are common in professional championship fights (historically)?", choices: ["3", "5", "12", "15"], correctIndex: "3" },
    { q: "Which sport is associated with the Stanley Cup?", choices: ["Baseball", "Ice hockey", "Basketball", "American football"], correctIndex: "2" },
    { q: "Which sport uses a shuttle and racquet?", choices: ["Badminton", "Tennis", "Squash", "Table tennis"], correctIndex: "1" },
    { q: "Which track and field event involves clearing a bar at height?", choices: ["Long jump", "Pole vault", "High jump", "Triple jump"], correctIndex: "3" },
    { q: "Which sport has positions called 'goalkeeper', 'defender', 'midfielder', and 'striker'?", choices: ["Basketball", "Rugby", "Soccer", "Baseball"], correctIndex: "3" },
    { q: "Which country hosted the 2008 Summer Olympics?", choices: ["China", "Greece", "UK", "Brazil"], correctIndex: "1" },
    { q: "Which sport uses a racket and a yellow ball on grass at Wimbledon?", choices: ["Tennis", "Badminton", "Squash", "Table tennis"], correctIndex: "1" },
    { q: "Which sport features a 'tee off' and 'putting green'?", choices: ["Baseball", "Cricket", "Golf", "Rugby"], correctIndex: "3" },
    { q: "Which sport is associated with the term 'slam dunk'?", choices: ["Basketball", "Volleyball", "Rugby", "Handball"], correctIndex: "1" },
    { q: "Which sport uses a net, court, and a ball and is played 5 vs 5?", choices: ["Handball", "Basketball", "Volleyball", "Futsal"], correctIndex: "2" },
    { q: "Which country is known for the rugby team All Blacks?", choices: ["Australia", "New Zealand", "South Africa", "England"], correctIndex: "2" },
    { q: "Which sport uses 'strike' and 'spare'?", choices: ["Cricket", "Bowling", "Baseball", "Bowls"], correctIndex: "2" },
    { q: "Which motor racing series is known as Formula 1?", choices: ["MotoGP", "Formula E", "Formula 1", "NASCAR"], correctIndex: "3" },
    { q: "Which sport's main international competition is the Cricket World Cup?", choices: ["Cricket", "Baseball", "Hockey", "Rugby"], correctIndex: "1" },
    { q: "Which sport uses a keel and mast on a boat?", choices: ["Rowing", "Sailing", "Canoeing", "Kayaking"], correctIndex: "2" },
    { q: "Which country held the Rugby World Cup in 2019?", choices: ["England", "Japan", "France", "South Africa"], correctIndex: "2" },
    { q: "In squash, the ball must hit which area to be in play?", choices: ["Back wall", "Side wall", "Front wall", "Ceiling"], correctIndex: "3" },
    { q: "Which sport awards the 'Green Jacket' to the winner?", choices: ["Horse racing", "Tennis", "Golf (Masters)", "Cricket"], correctIndex: "3" },
    { q: "Which sport involves synchronized swimming and routines?", choices: ["Artistic swimming", "Diving", "Water polo", "Swimming"], correctIndex: "1" },
    { q: "Which sport uses a 'third base', 'second base', and 'first base'?", choices: ["Baseball", "Cricket", "Rugby", "American football"], correctIndex: "1" },
    { q: "Which sport is played on a velodrome?", choices: ["Track cycling", "Speed skating", "Basketball", "Handball"], correctIndex: "1" },
    { q: "Which country hosts the football Champions League final commonly featuring European clubs?", choices: ["USA", "UEFA countries (Europe)", "South America", "Asia"], correctIndex: "2" },
    { q: "Which sport has a 'knockout' tournament stage?", choices: ["Golf", "Soccer", "Boxing", "Chess"], correctIndex: "2" },
    { q: "Which sport is measured in 'innings' and 'overs'?", choices: ["Baseball and Cricket", "Tennis and Badminton", "Basketball and Volleyball", "Rugby and Football"], correctIndex: "1" },
    { q: "Which athlete holds world records in sprinting like the 100m and 200m (example: Usain Bolt)?", choices: ["Usain Bolt", "Carl Lewis", "Yohan Blake", "Justin Gatlin"], correctIndex: "1" },
    { q: "Which sport is associated with the 'Heisman Trophy' in the USA?", choices: ["Baseball", "Basketball", "College American football", "Ice hockey"], correctIndex: "3" },
    { q: "Which racquet sport is played indoors with a small rubber ball and four walls?", choices: ["Tennis", "Squash", "Badminton", "Table tennis"], correctIndex: "2" },
    { q: "Which martial art is Japanese and focuses on throws and pins?", choices: ["Karate", "Taekwondo", "Judo", "Kung Fu"], correctIndex: "3" },
    { q: "Which sport uses lanes and starts from starting blocks in sprints?", choices: ["Swimming", "Athletics (track)", "Cycling", "Rowing"], correctIndex: "2" },
    { q: "Which winter sport involves sliding stones on ice?", choices: ["Curling", "Ice hockey", "Figure skating", "Bobsleigh"], correctIndex: "1" },
    { q: "Which sport uses a 'footvolley' combining soccer and volleyball skills?", choices: ["Beach volleyball", "Footvolley", "Sepak takraw", "Futsal"], correctIndex: "2" },
    { q: "Which sport uses a 'scrum' to restart play?", choices: ["Rugby", "Football (soccer)", "Hockey", "Basketball"], correctIndex: "1" }
  ],

  Electronics: [
    { q: "What is the unit of electrical resistance?", choices: ["Volt", "Ampere", "Ohm", "Watt"], correctIndex: "3" },
    { q: "What does LED stand for?", choices: ["Light Energy Device", "Low Energy Diode", "Light Emitting Diode", "Long Electrical Device"], correctIndex: "3" },
    { q: "Which component stores electrical charge?", choices: ["Resistor", "Inductor", "Capacitor", "Diode"], correctIndex: "3" },
    { q: "Which device converts AC to DC?", choices: ["Transformer", "Rectifier", "Amplifier", "Oscillator"], correctIndex: "2" },
    { q: "What is the function of a transistor?", choices: ["To store data", "To amplify or switch signals", "To measure current", "To reduce voltage"], correctIndex: "2" },
    { q: "Which component opposes current flow?", choices: ["Capacitor", "Resistor", "Inductor", "Transformer"], correctIndex: "2" },
    { q: "What is the unit of electric current?", choices: ["Volt", "Ampere", "Ohm", "Farad"], correctIndex: "2" },
    { q: "Which semiconductor material is most commonly used in electronics?", choices: ["Copper", "Silicon", "Aluminum", "Gold"], correctIndex: "2" },
    { q: "Which component allows current to flow in only one direction?", choices: ["Resistor", "Capacitor", "Diode", "Inductor"], correctIndex: "3" },
    { q: "Which device amplifies electrical signals?", choices: ["Antenna", "Rectifier", "Amplifier", "Filter"], correctIndex: "3" },
    { q: "Which unit measures capacitance?", choices: ["Henry", "Farad", "Ohm", "Watt"], correctIndex: "2" },
    { q: "Which component stores energy in a magnetic field?", choices: ["Capacitor", "Resistor", "Inductor", "Diode"], correctIndex: "3" },
    { q: "What is a breadboard used for?", choices: ["Permanent circuits", "Prototyping circuits", "Measuring voltage", "Soldering components"], correctIndex: "2" },
    { q: "Which measuring instrument measures voltage?", choices: ["Ammeter", "Voltmeter", "Ohmmeter", "Oscilloscope"], correctIndex: "2" },
    { q: "Which part of a transistor controls the current between collector and emitter?", choices: ["Base", "Gate", "Drain", "Source"], correctIndex: "1" },
    { q: "Which device converts electrical energy into light?", choices: ["Motor", "LED", "Transformer", "Capacitor"], correctIndex: "2" },
    { q: "Which component is used to protect circuits from excessive current?", choices: ["Fuse", "Resistor", "Capacitor", "Inductor"], correctIndex: "1" },
    { q: "What does PCB stand for?", choices: ["Printed Circuit Board", "Power Control Box", "Parallel Circuit Block", "Printed Current Board"], correctIndex: "1" },
    { q: "Which signal type represents information as continuous values?", choices: ["Digital", "Analog", "Binary", "Discrete"], correctIndex: "2" },
    { q: "Which logic gate outputs true only when both inputs are true?", choices: ["OR", "AND", "NOT", "XOR"], correctIndex: "2" },
    { q: "Which component changes electrical energy to mechanical motion?", choices: ["Motor", "LED", "Resistor", "Diode"], correctIndex: "1" },
    { q: "Which component limits current in a circuit?", choices: ["Capacitor", "Resistor", "Transistor", "Inductor"], correctIndex: "2" },
    { q: "Which term describes alternating direction of current?", choices: ["AC", "DC", "RC", "LC"], correctIndex: "1" },
    { q: "Which instrument shows a waveform of a signal?", choices: ["Multimeter", "Oscilloscope", "Signal generator", "Spectrum analyzer"], correctIndex: "2" },
    { q: "Which component blocks DC and passes AC?", choices: ["Capacitor", "Inductor", "Resistor", "Diode"], correctIndex: "1" },
    { q: "Which material is used for most wires due to good conductivity?", choices: ["Aluminum", "Iron", "Copper", "Plastic"], correctIndex: "3" },
    { q: "Which device increases or decreases AC voltage?", choices: ["Rectifier", "Transformer", "Amplifier", "Filter"], correctIndex: "2" },
    { q: "Which number indicates resistance value color code for gold tolerance?", choices: ["5%", "2%", "1%", "10%"], correctIndex: "1" },
    { q: "Which device is used to convert analog signals to digital?", choices: ["DAC", "ADC", "PLL", "Op-amp"], correctIndex: "2" },
    { q: "Which IC family is widely used for microcontrollers (8-bit)?", choices: ["ARM Cortex", "PIC/AVR", "FPGA", "TTL"], correctIndex: "2" },
    { q: "Which filter allows low frequencies to pass and blocks high?", choices: ["High-pass", "Band-pass", "Low-pass", "Notch"], correctIndex: "3" },
    { q: "Which component stores data in modern computers temporarily?", choices: ["ROM", "HDD", "RAM", "CD-ROM"], correctIndex: "3" },
    { q: "Which semiconductor device has three terminals in a BJT?", choices: ["Anode, Cathode, Gate", "Source, Drain, Gate", "Collector, Base, Emitter", "Input, Output, Ground"], correctIndex: "3" },
    { q: "Which factor measures how much a circuit resists current?", choices: ["Voltage", "Resistance", "Current", "Power"], correctIndex: "2" },
    { q: "Which coding converts analog amplitude to binary?", choices: ["Modulation", "Sampling & Quantization", "Amplification", "Filtering"], correctIndex: "2" },
    { q: "Which power supply type provides stable DC voltage?", choices: ["AC generator", "Battery", "Regulated DC supply", "Inductor"], correctIndex: "3" },
    { q: "Which device is used to step down mains voltage for low-voltage circuits?", choices: ["Rectifier", "Transformer", "Capacitor", "Inductor"], correctIndex: "2" },
    { q: "Which value measures stored electrical charge in capacitor?", choices: ["Ohm", "Henry", "Farad", "Volt"], correctIndex: "3" },
    { q: "What is the standard household AC mains frequency in many countries?", choices: ["50 or 60 Hz", "100 Hz", "400 Hz", "1 Hz"], correctIndex: "1" },
    { q: "Which device is used to convert DC to AC?", choices: ["Rectifier", "Inverter", "Transformer", "Amplifier"], correctIndex: "2" },
    { q: "Which parameter is measured in watts?", choices: ["Voltage", "Current", "Power", "Resistance"], correctIndex: "3" },
    { q: "Which component provides isolation and impedance matching in audio circuits?", choices: ["Transformer", "Diode", "Transistor", "Capacitor"], correctIndex: "1" },
    { q: "Which amplifier configuration is common-emitter in BJT analogous to in MOSFET?", choices: ["Common-source", "Common-drain", "Common-gate", "Common-collector"], correctIndex: "1" },
    { q: "Which filter type removes a narrow band of frequencies?", choices: ["Low-pass", "High-pass", "Band-pass", "Notch"], correctIndex: "4" },
    { q: "Which logic family uses CMOS technology?", choices: ["TTL", "ECL", "CMOS", "RTL"], correctIndex: "3" },
    { q: "Which component is frequently used to store data permanently?", choices: ["RAM", "SSD/HDD", "Cache", "Register"], correctIndex: "2" },
    { q: "Which device measures current?", choices: ["Voltmeter", "Ammeter", "Ohmmeter", "Wattmeter"], correctIndex: "2" },
    { q: "Which parameter is described by V = I * R?", choices: ["Power equation", "Ohm's law", "Kirchhoff's law", "Faraday's law"], correctIndex: "2" },
    { q: "Which unit measures frequency?", choices: ["Hertz", "Ohm", "Watt", "Volt"], correctIndex: "1" },
    { q: "What does PWM stand for?", choices: ["Pulse Width Modulation", "Power Wave Modulation", "Phase Width Modulation", "Pulse Wave Measurement"], correctIndex: "1" },
    { q: "Which component is used to block reverse polarity protection?", choices: ["Resistor", "Diode", "Capacitor", "Inductor"], correctIndex: "2" },
    { q: "Which electronic device is used as a switch and amplifier in circuits?", choices: ["Diode", "Transistor", "Resistor", "Capacitor"], correctIndex: "2" },
    { q: "Which type of diode emits light when forward biased?", choices: ["Zener diode", "Schottky diode", "LED", "Tunnel diode"], correctIndex: "3" },
    { q: "Which measurement tells how loud a sound is?", choices: ["Hertz", "Decibel", "Volt", "Ohm"], correctIndex: "2" },
    { q: "Which device stores a single bit in digital electronics?", choices: ["Flip-flop", "Op-amp", "Resistor", "LED"], correctIndex: "1" },
    { q: "Which IC is commonly used for operational amplification?", choices: ["555 timer", "Op-amp (e.g., LM741)", "Microcontroller", "Shift register"], correctIndex: "2" },
    { q: "What is the typical logic high voltage for TTL logic?", choices: ["0V", "5V", "3.3V", "12V"], correctIndex: "2" },
    { q: "Which device generates a repeating electrical signal (clock)?", choices: ["Oscillator", "Rectifier", "Amplifier", "Filter"], correctIndex: "1" },
    { q: "Which component reduces ripple in a power supply?", choices: ["Inductor", "Rectifier", "Filter capacitor", "Transformer"], correctIndex: "3" },
    { q: "Which term describes converting digital to analog?", choices: ["ADC", "DAC", "Modulation", "Quantization"], correctIndex: "2" },
    { q: "Which technology is used in many modern microcontrollers for low power?", choices: ["TTL", "CMOS", "ECL", "RTL"], correctIndex: "2" },
    { q: "Which is used as reference ground in circuits?", choices: ["Vcc", "Vdd", "GND", "Vref"], correctIndex: "3" },
    { q: "Which device is used to protect circuits from voltage spikes?", choices: ["Transistor", "Zener diode", "Fuse", "Resistor"], correctIndex: "2" },
    { q: "Which element is primarily used as a semiconductor dopant to create n-type silicon?", choices: ["Boron", "Phosphorus", "Aluminum", "Gold"], correctIndex: "2" },
    { q: "Which display technology uses tiny liquid crystals?", choices: ["OLED", "LCD", "CRT", "Plasma"], correctIndex: "2" },
    { q: "Which protocol is commonly used for wired Ethernet?", choices: ["Wi-Fi", "Bluetooth", "IEEE 802.3", "Zigbee"], correctIndex: "3" },
    { q: "Which component changes current to voltage in sensors often (shunt)?", choices: ["Resistor", "Inductor", "Capacitor", "Diode"], correctIndex: "1" },
    { q: "Which memory is non-volatile and can be electrically erased and reprogrammed?", choices: ["RAM", "EEPROM/Flash", "Cache", "Register"], correctIndex: "2" }
  ]
};

export default QUESTIONS;
