const QUESTIONS = {
  Geography: [
    { q: "What is the capital of Australia?", choices: ["Canberra", "Sydney", "Melbourne", "Perth"], img:"Img/austrailia.webp", correctIndex: "1" },
    { q: "Which is the largest ocean on Earth?", choices: ["Atlantic Ocean", "Indian Ocean", "Pacific Ocean", "Arctic Ocean"], img:"Img/pacific.webp", correctIndex: "3" },
    { q: "Which country has the largest population?", choices: ["India", "Russia", "USA", "China"], img:"Img/china.webp", correctIndex: "1" },
    { q: "What is the longest river in the world?", choices: ["Nile", "Amazon", "Yangtze", "Mississippi"], img:"Img/nile.webp", correctIndex: "1" },
    { q: "Which continent is Egypt in?", choices: ["Asia", "Africa", "Europe", "South America"], img:"Img/egypt.webp", correctIndex: "2" },
    { q: "What is the capital of France?", choices: ["Paris", "Lyon", "Marseille", "Nice"], img:"Img/france.webp", correctIndex: "1" },
    { q: "Mount Everest is located in which mountain range?", choices: ["Andes", "Rockies", "Himalayas", "Alps"], img:"Img/everest.webp", correctIndex: "3" },
    { q: "Which US state is the Grand Canyon located in?", choices: ["Utah", "Arizona", "Nevada", "Colorado"], img:"Img/grand.webp", correctIndex: "2" },
    { q: "Which European country has the most people?", choices: ["Germany", "France", "UK", "Italy"], img:"Img/europ.webp", correctIndex: "1" },
    { q: "What is the capital of Japan?", choices: ["Osaka", "Hiroshima", "Kyoto", "Tokyo"], img:"Img/japan.webp", correctIndex: "4" },
    { q: "Which desert is the largest hot desert in the world?", choices: ["Gobi", "Sahara", "Kalahari", "Mojave"], img:"Img/deserts.webp", correctIndex: "2" },
    { q: "Which river runs through London?", choices: ["Thames", "Seine", "Danube", "Rhine"], img:"Img/londonr.webp", correctIndex: "1" },
    { q: "Which country is the island of Borneo shared by?", choices: ["Indonesia, Malaysia, Brunei", "Philippines, Indonesia", "Malaysia, Thailand", "Brunei, Philippines"], img:"Img/borneo.webp", correctIndex: "1" },
    { q: "What is the capital of Canada?", choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"], img:"Img/canadas.webp", correctIndex: "3" },
    { q: "Which country contains the city of Marrakech?", choices: ["Morocco", "Algeria", "Tunisia", "Egypt"], img:"Img/Marrakech.webp", correctIndex: "1" },
    { q: "Which U.S. city is famous for its Golden Gate Bridge?", choices: ["Los Angeles", "San Francisco", "Seattle", "San Diego"], img:"Img/goldengate.webp", correctIndex: "3" },
    { q: "Which is the smallest country by area?", choices: ["Monaco", "Nauru", "Vatican City", "San Marino"], img:"Img/smallcountry.webp", correctIndex: "3" },
    { q: "Which African country has the largest land area?", choices: ["Egypt", "Algeria", "Sudan", "Libya"], img:"Img/largearea.webp", correctIndex: "2" },
    { q: "Which ocean is on the east coast of the United States?", choices: ["Pacific", "Atlantic", "Indian", "Arctic"], img:"Img/coastwebp.webp", correctIndex: "2" },
    { q: "Which country has cities named Córdoba and Seville?", choices: ["Portugal", "Argentina", "Mexico", "Spain"], img:"Img/Córdoba.webp", correctIndex: "4" },
    { q: "The Rhine river flows into which sea?", choices: ["Baltic Sea", "North Sea", "Mediterranean Sea", "Black Sea"], img:"Img/Rhine.webp", correctIndex: "1" },
    { q: "Which country is famous for the fjords?", choices: ["Sweden", "Norway", "Finland", "Denmark"], img:"Img/fjords.webp", correctIndex: "2" },
    { q: "What is the capital of Italy?", choices: ["Venice", "Rome", "Florence", "Milan"], img:"Img/italy.webp", correctIndex: "2" },
    { q: "Which country is the Taj Mahal located in?", choices: ["Pakistan", "India", "Bangladesh", "Nepal"], img:"Img/tajmahal.webp", correctIndex: "2" },
    { q: "Which US state is known as the 'Sunshine State'?", choices: ["California", "Florida", "Texas", "Arizona"], img:"Img/sunshine.webp", correctIndex: "2" },
    { q: "Which continent is Chile located in?", choices: ["South America", "North America", "Africa", "Europe"], img:"Img/chiles.webp", correctIndex: "1" },
    { q: "Which city is the capital of Germany?", choices: ["Munich", "Frankfurt", "Berlin", "Hamburg"], img:"Img/berlin.webp", correctIndex: "3" },
    { q: "Which country has the most natural lakes?", choices: ["Canada", "USA", "Russia", "Finland"], img:"Img/lakes.webp", correctIndex: "1" },
    { q: "What is the capital of Russia?", choices: ["Saint Petersburg", "Kazan", "Moscow", "Sochi"], img:"Img/putin.webp", correctIndex: "3" },
    { q: "Which mountain is the highest in Africa?", choices: ["Mount Kenya", "Rwenzori", "Kilimanjaro", "Atlas"], img:"Img/cape.webp", correctIndex: "3" },
    { q: "Which river flows through Paris?", choices: ["Seine", "Loire", "Rhône", "Garonne"], img:"Img/river.webp", correctIndex: "1" },
    { q: "Which country is known as the Land of the Rising Sun?", choices: ["China", "Japan", "Korea", "Thailand"], img:"Img/rise.webp", correctIndex: "2" },
    { q: "Which European capital is built on approximately 118 islands?", choices: ["Stockholm", "Helsinki", "Copenhagen", "Oslo"], img:"Img/island.webp", correctIndex: "1" },
    { q: "Which country contains the lakes of Plitvice?", choices: ["Croatia", "Slovenia", "Bosnia", "Serbia"], img:"Img/Plitvice.webp", correctIndex: "1" },
    { q: "Which is the largest island in the Mediterranean Sea?", choices: ["Sardinia", "Sicily", "Corsica", "Crete"], img:"Img/Mediterranean.webp", correctIndex: "2" }
  ],
    

  

  Science: [
    { q: "What is the chemical symbol for water?", choices: ["HO", "H2O", "O2", "H2"], correctIndex: "2" },
    { q: "What gas do plants absorb from the atmosphere?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"], correctIndex: "2" },
    { q: "What part of the cell contains DNA?", choices: ["Nucleus", "Mitochondria", "Ribosome", "Cytoplasm"], correctIndex: "1" },
    { q: "What force pulls objects toward Earth?", choices: ["Magnetism", "Gravity", "Inertia", "Friction"], correctIndex: "2" },
    { q: "What is the boiling point of water?", choices: ["50°C", "100°C", "150°C", "200°C"], correctIndex: "2" },
    { q: "What is the chemical symbol for table salt (sodium chloride)?", choices: ["NaCl", "KCl", "ClNa", "NaK"], correctIndex: "1" },
    { q: "What organ pumps blood through the body?", choices: ["Liver", "Kidney", "Heart", "Lungs"], correctIndex: "3" },
    { q: "Which planet is known as the Red Planet?", choices: ["Venus", "Mars", "Jupiter", "Mercury"], correctIndex: "2" },
    { q: "What is the center of an atom called?", choices: ["Electron", "Proton", "Nucleus", "Neutron"], correctIndex: "3" },
    { q: "Which gas do humans breathe out?", choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Helium"], correctIndex: "2" },
    { q: "What type of bond involves sharing electron pairs?", choices: ["Ionic", "Covalent", "Metallic", "Hydrogen"], correctIndex: "2" },
    { q: "What is the study of living organisms called?", choices: ["Physics", "Chemistry", "Biology", "Geology"], correctIndex: "3" },
    { q: "Which organelle is the powerhouse of the cell?", choices: ["Ribosome", "Mitochondria", "Nucleus", "Golgi apparatus"], correctIndex: "2" },
    { q: "What kind of celestial object is the Sun?", choices: ["Planet", "Star", "Moon", "Asteroid"], correctIndex: "2" },
    { q: "What is the chemical formula for carbon dioxide?", choices: ["CO", "CO2", "O2", "C2O"], correctIndex: "2" },
    { q: "What is the unit of electrical current?", choices: ["Volt", "Ohm", "Ampere", "Watt"], correctIndex: "3" },
    { q: "Which particle has a negative charge?", choices: ["Proton", "Neutron", "Electron", "Photon"], correctIndex: "3" },
    { q: "Which planet has the most moons (as of common knowledge)?", choices: ["Earth", "Mars", "Jupiter", "Venus"], correctIndex: "3" },
    { q: "Which gas makes up most of Earth's atmosphere?", choices: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon Dioxide"], correctIndex: "3" },
    { q: "What is the natural satellite of the Earth?", choices: ["Mars", "Moon", "Venus", "Jupiter"], correctIndex: "2" },
    { q: "What is the primary source of energy for the water cycle?", choices: ["Wind", "Sun", "Moon", "Geothermal"], correctIndex: "2" },
    { q: "Which scale measures the acidity of a solution?", choices: ["Fahrenheit", "pH", "Richter", "Decibel"], correctIndex: "2" },
    { q: "What is the SI unit of temperature?", choices: ["Celsius", "Fahrenheit", "Kelvin", "Rankine"], correctIndex: "3" },
    { q: "Which element has the atomic number 1?", choices: ["Helium", "Hydrogen", "Lithium", "Carbon"], correctIndex: "2" },
    { q: "Which force keeps planets in orbit around the Sun?", choices: ["Magnetism", "Gravity", "Friction", "Electricity"], correctIndex: "2" },
    { q: "What is the process by which plants make food using sunlight?", choices: ["Respiration", "Photosynthesis", "Transpiration", "Fermentation"], correctIndex: "2" },
    { q: "Which type of wave is sound?", choices: ["Transverse", "Longitudinal", "Electromagnetic", "Torsional"], correctIndex: "2" },
    { q: "What is HCl in chemistry?", choices: ["Hydrochloric acid", "Hydrogen chloride gas", "Helium chloride", "Hydrated chloride"], correctIndex: "1" },
    { q: "Which organ filters blood to make urine?", choices: ["Liver", "Kidney", "Heart", "Lung"], correctIndex: "2" },
    { q: "Which planet is the largest in our solar system?", choices: ["Saturn", "Jupiter", "Neptune", "Uranus"], correctIndex: "2" },
    { q: "What do you call a group of atoms bonded together?", choices: ["Element", "Molecule", "Ion", "Compound"], correctIndex: "2" },
    { q: "What is the study of rocks called?", choices: ["Biology", "Geology", "Meteorology", "Zoology"], correctIndex: "2" },
    { q: "Which part of the human body controls balance?", choices: ["Cerebellum", "Cortex", "Medulla", "Hypothalamus"], correctIndex: "1" },
    { q: "What is the common name for sodium bicarbonate?", choices: ["Baking soda", "Table salt", "Bleach", "Vinegar"], correctIndex: "1" },
    { q: "Which gas is essential for respiration?", choices: ["Helium", "Oxygen", "Nitrogen", "Methane"], correctIndex: "2" },
    
  ],
  

  Sport: [
    { q: "How many players from one team are on the field in soccer?", choices: ["9", "10", "11", "12"], correctIndex: "3" },
    { q: "In basketball, how many points is a free throw worth?", choices: ["1", "2", "3", "4"], correctIndex: "1" },
    { q: "Which sport uses a shuttlecock?", choices: ["Tennis", "Badminton", "Squash", "Cricket"], correctIndex: "2" },
    { q: "How long is an Olympic swimming pool?", choices: ["25m", "50m", "75m", "100m"], correctIndex: "2" },
    { q: "In which sport do players hit a ball with a bat?", choices: ["Volleyball", "Hockey", "Cricket", "Rowing"], correctIndex: "3" },
    { q: "How many players are on a basketball team on the court?", choices: ["4", "5", "6", "7"], correctIndex: "2" },
    { q: "Which country hosted the 2016 Summer Olympics?", choices: ["China", "Brazil", "UK", "Russia"], correctIndex: "2" },
    { q: "How many minutes are in a standard soccer match (excluding extra time)?", choices: ["90", "60", "120", "45"], correctIndex: "1" },
    { q: "What sport uses a pommel horse?", choices: ["Diving", "Gymnastics", "Equestrian", "Wrestling"], correctIndex: "2" },
    { q: "What is a 'strike' in baseball?", choices: ["A missed catch", "A successful hit", "A failed swing or missed pitch", "A home run"], correctIndex: "3" },
    { q: "In tennis, what is the score when a player wins the point after deuce?", choices: ["Match", "Game", "Advantage", "Set"], correctIndex: "3" },
    { q: "Which sport is Roger Federer famous for?", choices: ["Golf", "Tennis", "Soccer", "Rugby"], correctIndex: "2" },
    { q: "What is the length of an NBA basketball court (in feet)?", choices: ["82", "94", "100", "110"], correctIndex: "2" },
    { q: "Which sport is known as the 'king of sports' globally?", choices: ["Cricket", "Basketball", "Tennis", "Football (soccer)"], correctIndex: "4" },
    { q: "How many players are on a rugby union team on the field?", choices: ["11", "13", "15", "7"], correctIndex: "3" },
    { q: "A 'hat-trick' in soccer means:", choices: ["Three assists", "Three goals by one player in a match", "Three appearances", "Three wins"], correctIndex: "2" },
    { q: "Which sport uses a puck?", choices: ["Tennis", "Ice hockey", "Field hockey", "Lacrosse"], correctIndex: "2" },
    { q: "How long is an Olympic marathon (approx.)?", choices: ["26.2 miles", "13.1 miles", "30 miles", "10 km"], correctIndex: "1" },
    { q: "Which country won the FIFA World Cup in 2018?", choices: ["Brazil", "Germany", "France", "Argentina"], correctIndex: "3" },
    { q: "In which sport would you use a javelin?", choices: ["Shot put", "Discus", "Javelin throw", "High jump"], correctIndex: "3" },
    { q: "What is the scoring method for a touchdown in American football?", choices: ["2 points", "3 points", "6 points", "1 point"], correctIndex: "3" },
    { q: "Which sport uses terms like 'birdie' and 'eagle'?", choices: ["Golf", "Tennis", "Badminton", "Cricket"], correctIndex: "1" },
    { q: "How many holes are there in a standard golf course?", choices: ["9", "12", "18", "24"], correctIndex: "3" },
    { q: "Which country hosted the 2012 Summer Olympics?", choices: ["China", "Brazil", "UK", "Russia"], correctIndex: "3" },
    { q: "How many periods are in an ice hockey game (professional)?", choices: ["2", "3", "4", "5"], correctIndex: "2" },
    { q: "Which sport uses a vault, rings, and parallel bars?", choices: ["Swimming", "Gymnastics", "Athletics", "Diving"], correctIndex: "2" },
    { q: "Which athlete is known for winning 9 Olympic gold medals in swimming (Michael Phelps)?", choices: ["Usain Bolt", "Michael Phelps", "Ian Thorpe", "Ryan Lochte"], correctIndex: "2" },
    { q: "Which country is famous for cricket and the Ashes rivalry with England?", choices: ["India", "Australia", "South Africa", "Pakistan"], correctIndex: "2" },
    { q: "What is the maximum score in ten-pin bowling for a single game?", choices: ["200", "250", "300", "350"], correctIndex: "3" },
    { q: "Which sport uses a 'tee' to start play?", choices: ["Tennis", "Cricket", "Golf", "Rugby"], correctIndex: "3" },
    { q: "Which country hosted the first modern Olympics in 1896?", choices: ["France", "Greece", "UK", "USA"], correctIndex: "2" },
    { q: "Which sport features the Tour de France?", choices: ["Running", "Cycling", "Swimming", "Rowing"], correctIndex: "2" },
    { q: "How many players are on a water polo team in the pool (per side)?", choices: ["5", "6", "7", "8"], correctIndex: "3" },
    { q: "Which sport uses terms like 'scrum' and 'try'?", choices: ["Rugby", "Soccer", "Cricket", "Basketball"], correctIndex: "1" },
    { q: "Which event is 100 meters long?", choices: ["Sprint", "Marathon", "Hurdles", "Relay"], correctIndex: "1" },
    
    
  ],

  Electronics: [
    { q: "What is the unit of electrical resistance?", choices: ["Volt", "Ampere", "Ohm", "Watt"], correctIndex: "3" },
    { q: "What does LED stand for?", choices: ["Light Energy Device", "Low Energy Diode", "Light Emitting Diode", "Long Electrical Device"], correctIndex: "3" },
    { q: "Which component stores electrical charge?", choices: ["Resistor", "Inductor", "Capacitor", "Diode"], correctIndex: "3" },
    { q: "Which device converts AC to DC?", choices: ["Transformer", "Rectifier", "Amplifier", "Oscillator"], correctIndex: "2" },
    { q: "What is the function of a transistor?", choices: ["To store data", "To amplify or switch signals", "To measure current", "To reduce voltage"], correctIndex: "2" },
    { q: "Which component opposes current flow?", choices: ["Capacitor", "Resistor", "Inductor", "Transformer"], correctIndex: "2" },
    { q: "What is the unit of electric current?", choices: ["Volt", "Ampere", "Ohm", "Farad"], correctIndex: "2" },
    { q: "Which semiconductor material is most commonly used in electronics?", choices: ["Copper", "Silicon", "Aluminum", "Gold"], correctIndex: "2" },
    { q: "Which component allows current to flow in only one direction?", choices: ["Resistor", "Capacitor", "Diode", "Inductor"], correctIndex: "3" },
    { q: "Which device amplifies electrical signals?", choices: ["Antenna", "Rectifier", "Amplifier", "Filter"], correctIndex: "3" },
    { q: "Which unit measures capacitance?", choices: ["Henry", "Farad", "Ohm", "Watt"], correctIndex: "2" },
    { q: "Which component stores energy in a magnetic field?", choices: ["Capacitor", "Resistor", "Inductor", "Diode"], correctIndex: "3" },
    { q: "What is a breadboard used for?", choices: ["Permanent circuits", "Prototyping circuits", "Measuring voltage", "Soldering components"], correctIndex: "2" },
    { q: "Which measuring instrument measures voltage?", choices: ["Ammeter", "Voltmeter", "Ohmmeter", "Oscilloscope"], correctIndex: "2" },
    { q: "Which part of a transistor controls the current between collector and emitter?", choices: ["Base", "Gate", "Drain", "Source"], correctIndex: "1" },
    { q: "Which device converts electrical energy into light?", choices: ["Motor", "LED", "Transformer", "Capacitor"], correctIndex: "2" },
    { q: "Which component is used to protect circuits from excessive current?", choices: ["Fuse", "Resistor", "Capacitor", "Inductor"], correctIndex: "1" },
    { q: "What does PCB stand for?", choices: ["Printed Circuit Board", "Power Control Box", "Parallel Circuit Block", "Printed Current Board"], correctIndex: "1" },
    { q: "Which signal type represents information as continuous values?", choices: ["Digital", "Analog", "Binary", "Discrete"], correctIndex: "2" },
    { q: "Which logic gate outputs true only when both inputs are true?", choices: ["OR", "AND", "NOT", "XOR"], correctIndex: "2" },
    { q: "Which component changes electrical energy to mechanical motion?", choices: ["Motor", "LED", "Resistor", "Diode"], correctIndex: "1" },
    { q: "Which component limits current in a circuit?", choices: ["Capacitor", "Resistor", "Transistor", "Inductor"], correctIndex: "2" },
    { q: "Which term describes alternating direction of current?", choices: ["AC", "DC", "RC", "LC"], correctIndex: "1" },
    { q: "Which instrument shows a waveform of a signal?", choices: ["Multimeter", "Oscilloscope", "Signal generator", "Spectrum analyzer"], correctIndex: "2" },
    { q: "Which component blocks DC and passes AC?", choices: ["Capacitor", "Inductor", "Resistor", "Diode"], correctIndex: "1" },
    { q: "Which material is used for most wires due to good conductivity?", choices: ["Aluminum", "Iron", "Copper", "Plastic"], correctIndex: "3" },
    { q: "Which device increases or decreases AC voltage?", choices: ["Rectifier", "Transformer", "Amplifier", "Filter"], correctIndex: "2" },
    { q: "Which number indicates resistance value color code for gold tolerance?", choices: ["5%", "2%", "1%", "10%"], correctIndex: "1" },
    { q: "Which device is used to convert analog signals to digital?", choices: ["DAC", "ADC", "PLL", "Op-amp"], correctIndex: "2" },
    { q: "Which IC family is widely used for microcontrollers (8-bit)?", choices: ["ARM Cortex", "PIC/AVR", "FPGA", "TTL"], correctIndex: "2" },
    { q: "Which filter allows low frequencies to pass and blocks high?", choices: ["High-pass", "Band-pass", "Low-pass", "Notch"], correctIndex: "3" },
    { q: "Which component stores data in modern computers temporarily?", choices: ["ROM", "HDD", "RAM", "CD-ROM"], correctIndex: "3" },
    { q: "Which semiconductor device has three terminals in a BJT?", choices: ["Anode, Cathode, Gate", "Source, Drain, Gate", "Collector, Base, Emitter", "Input, Output, Ground"], correctIndex: "3" },
    { q: "Which factor measures how much a circuit resists current?", choices: ["Voltage", "Resistance", "Current", "Power"], correctIndex: "2" },
    { q: "Which coding converts analog amplitude to binary?", choices: ["Modulation", "Sampling & Quantization", "Amplification", "Filtering"], correctIndex: "2" },
    
  ]
};

export default QUESTIONS;
